spring.application.name=backend

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pricetracker
spring.datasource.username=root
spring.datasource.password=Neeraj321.

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=PriceTrackerSecretKeyPriceTrackerSecretKey
jwt.expiration=86400000

# ===============================
# SCRAPER CONFIG
# ===============================
app.scraper.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
app.scraper.timeout=10000
# ===============================
# EMAIL CONFIG
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=neeraj200430@gmail.com
spring.mail.password=jzns caqp xdnw qgha

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# VAPID CONFIG (For Web Push)
# ===============================
# If left blank, the server will automatically generate a secure VAPID keypair on startup!
vapid.public.key=
vapid.private.key=
vapid.subject=mailto:neeraj200430@gmail.com